// Package events defines the platform's CloudEvents 1.0 contract: the envelope
// types every service publishes to Kafka and the subject/type constants shared
// by producers (outbox relays) and consumers (audit, webhooks, workflows).
//
// Phase 27 scope: contract freeze only (types + schema catalog).
// Phase 28 adds the SDK around it:
//
//   - Producer / KafkaProducer — publish an envelope to the events topic.
//   - Consumer — consumer-group member with retries + DLQ routing.
//   - OutboxEvent + GormOutboxStore — transactional outbox (append inside the
//     business DB transaction).
//   - Relay — interval/batch worker that moves outbox rows to Kafka.
//   - EnsureTopics — idempotent startup provisioning for a service's topic
//     and DLQ topic. Services MUST call this before starting their producer /
//     consumer so the first publish cannot race broker topic creation.
//
// Delivery is at-least-once end to end: the relay may republish an event after
// a crash between Kafka ack and MarkSent, and consumers commit only after a
// handler succeeds or the event is dead-lettered. Handlers must be idempotent.
package events

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"time"
)

// CloudEvent is the CloudEvents 1.0 JSON envelope (subset used by the platform).
type CloudEvent struct {
	// SpecVersion is always "1.0".
	SpecVersion string `json:"specversion"`
	// ID is a unique event id (generated by the producer).
	ID string `json:"id"`
	// Source identifies the originating service (e.g. "content-service").
	Source string `json:"source"`
	// Type is the full event type, e.g. "org.omoikane.content.post.published.v1".
	Type string `json:"type"`
	// Subject is the entity reference, e.g. "post/42" (optional).
	Subject string `json:"subject,omitempty"`
	// Time is the RFC3339Nano event timestamp.
	Time time.Time `json:"time"`
	// Data holds the event payload (see schemas/ for JSON Schema).
	Data json.RawMessage `json:"data"`
}

// NewEventID returns a random 128-bit hex event id suitable for CloudEvent "id".
// Generated with crypto/rand (not math/rand) so ids are unpredictable across
// peers and cannot collide.
func NewEventID() string {
	buf := make([]byte, 16)
	if _, err := rand.Read(buf); err != nil {
		// crypto/rand failures are unrecoverable in practice; generate from the
		// current time so a broken platform cannot hard-fail a business request.
		return fmt.Sprintf("%d", time.Now().UnixNano())
	}
	return hex.EncodeToString(buf)
}

// Platform event type prefixes.
const (
	SourceAuth     = "auth-service"
	SourceContent  = "content-service"
	SourceMedia    = "media-service"
	SourceMessages = "messages-service"
	SourceSettings = "settings-service"

	TypeUserRegistered  = "org.omoikane.auth.user.registered.v1"
	TypeAuthLogin       = "org.omoikane.auth.login.v1"
	TypePagePublished   = "org.omoikane.content.page.published.v1"
	TypePageUpdated     = "org.omoikane.content.page.updated.v1"
	TypePostPublished   = "org.omoikane.content.post.published.v1"
	TypePostUpdated     = "org.omoikane.content.post.updated.v1"
	TypeMediaUploaded   = "org.omoikane.media.uploaded.v1"
	TypeMessageCreated  = "org.omoikane.messages.message.created.v1"
	TypeContactReceived = "org.omoikane.messages.contact.received.v1"
	TypeSettingsUpdated = "org.omoikane.settings.updated.v1"
)
