// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/blog" | "/admin/blog/categories" | "/admin/blog/tags" | "/admin/media" | "/admin/messages" | "/admin/pages" | "/admin/settings" | "/admin/users" | "/blog" | "/blog/[slug]" | "/forgot-password" | "/login" | "/pages/[...slug]" | "/preview/[id]" | "/register" | "/settings" | "/setup"
type AppRouteHandlerRoutes = "/api/auth/forgot-password" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/register" | "/api/blog/categories" | "/api/blog/categories/[id]" | "/api/blog/posts" | "/api/blog/posts/[id]" | "/api/blog/posts/[id]/like" | "/api/blog/tags" | "/api/blog/tags/[id]" | "/api/dashboard/stats" | "/api/media" | "/api/media/[id]" | "/api/messages" | "/api/messages/[id]/read" | "/api/messages/read-all" | "/api/pages" | "/api/pages/[id]" | "/api/pages/reorder" | "/api/pages/slug" | "/api/settings" | "/api/settings/password" | "/api/settings/profile" | "/api/setup" | "/api/users" | "/api/users/[id]" | "/rss"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/blog": {}
  "/admin/blog/categories": {}
  "/admin/blog/tags": {}
  "/admin/media": {}
  "/admin/messages": {}
  "/admin/pages": {}
  "/admin/settings": {}
  "/admin/users": {}
  "/api/auth/forgot-password": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/register": {}
  "/api/blog/categories": {}
  "/api/blog/categories/[id]": { "id": string; }
  "/api/blog/posts": {}
  "/api/blog/posts/[id]": { "id": string; }
  "/api/blog/posts/[id]/like": { "id": string; }
  "/api/blog/tags": {}
  "/api/blog/tags/[id]": { "id": string; }
  "/api/dashboard/stats": {}
  "/api/media": {}
  "/api/media/[id]": { "id": string; }
  "/api/messages": {}
  "/api/messages/[id]/read": { "id": string; }
  "/api/messages/read-all": {}
  "/api/pages": {}
  "/api/pages/[id]": { "id": string; }
  "/api/pages/reorder": {}
  "/api/pages/slug": {}
  "/api/settings": {}
  "/api/settings/password": {}
  "/api/settings/profile": {}
  "/api/setup": {}
  "/api/users": {}
  "/api/users/[id]": { "id": string; }
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/forgot-password": {}
  "/login": {}
  "/pages/[...slug]": { "slug": string[]; }
  "/preview/[id]": { "id": string; }
  "/register": {}
  "/rss": {}
  "/settings": {}
  "/setup": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
