// Command docs is the Omoikane API documentation service (Phase 31, Wave 3).
//
// After the monolith (cmd/api) was retired, the main API's Swagger UI needed a
// home: this tiny service serves it on DOCS_PORT (default 8089) via httpSwagger
// against the docs generated by `make swagger` (backend/docs, embedded in
// backend/docs/docs.go). The nginx gateway routes /api/swagger/ here with a
// trailing-slash redirect rewrite.
//
// Swagger generation anchors on THIS file (`swag init -g cmd/docs/main.go`):
// it imports the handler package so swag scans every route annotation, and the
// general API metadata (@title/@BasePath /api/@securityDefinitions) lives here.
package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	_ "omoikane-backend/docs"
	"omoikane-backend/internal/handlers"

	httpSwagger "github.com/swaggo/http-swagger"
)

// @title Omoikane API
// @version 1.0
// @description REST API for the Omoikane CMS. Public endpoints do not require authentication; protected endpoints accept a Bearer token (or the session cookie set by login). Admin-only endpoints require an admin role.
// @contact.name Omoikane
// @BasePath /api
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
func main() {
	port := os.Getenv("DOCS_PORT")
	if port == "" {
		port = "8089"
	}

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	mux := http.NewServeMux()

	// Health (readiness check from Makefile / compose healthcheck)
	mux.HandleFunc("GET /health", handlers.HealthHandler)

	// Swagger UI (public). httpSwagger emits the HTML UI + a trailing-slash
	// redirect; nginx rewrites the /swagger/ redirect so the prefixed URL
	// /api/swagger/ resolves.
	mux.HandleFunc("GET /swagger/", httpSwagger.Handler())

	addr := ":" + port
	log.Printf("docs-service starting on %s", addr)
	srv := &http.Server{Addr: addr, Handler: mux}
	go func() {
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("docs-service failed: %v", err)
		}
	}()

	<-ctx.Done()
	log.Println("docs-service shutting down")
	shutdownCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := srv.Shutdown(shutdownCtx); err != nil {
		log.Printf("docs-service: shutdown error: %v", err)
	}
}

// newDocsMux registers the docs-service routes. Exposed as a function so
// cmd/docs tests can exercise the wiring.
func newDocsMux() *http.ServeMux {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /health", handlers.HealthHandler)
	mux.HandleFunc("GET /swagger/", httpSwagger.Handler())
	return mux
}
